CC=g++
CFLAGS=-O0 -std=c++17

all: fifth twenty-sixth

fifth:
	$(CC) $(CFLAGS) fifth.cpp -o fifth

twenty-sixth:
	$(CC) $(CFLAGS) twenty-sixth.cpp -o twenty-sixth

clean:
	rm -f fifth
	rm -f twenty-sixth